version: '3.8'

services:
  instagram-crawler-api:
    build: .
    container_name: instagram-crawler-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      # Optional environment variables for proxy configuration
      # - PROXY_SERVICE_API_KEY=your_proxy_service_api_key
      # - DEFAULT_PROXY=http://user:pass@host:port
      # Optional: Use host network mode to access the host's IP address
      # Uncomment the next line to use the host's network stack
      # network_mode: "host"
      # Alternative: Use a specific network
    networks:
      - instagram-network
    command: [ "uvicorn", "instagram_api_service:app", "--host", "0.0.0.0", "--port", "8000" ]

networks:
  instagram-network:
    driver: bridge
